
import java.awt.CardLayout;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.GroupLayout;





public class prototype extends javax.swing.JFrame {
    public static int stepN = 0;
    public static int numberOfSteps = 0;
    public static int startingStep = 1;
    
    HeartBeatReceiving HB = new HeartBeatReceiving();
    HeartBeatSending HBS = new HeartBeatSending();
    DataCollection DC = new DataCollection();
    Thread threadHB = new Thread(HB);
    Thread threadDC = new Thread(DC);
    Thread threadHBS = new Thread(HBS);
    
    /**
     * Creates new form prototype
     */
    public prototype() {
        initComponents();
        viewPartialBtn.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        coordinates = new javax.swing.JDialog();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        jSpinner4 = new javax.swing.JSpinner();
        jSpinner5 = new javax.swing.JSpinner();
        jSpinner6 = new javax.swing.JSpinner();
        jSpinner7 = new javax.swing.JSpinner();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sending = new javax.swing.JOptionPane();
        map = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JLayeredPane();
        dronesPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        textArea2 = new java.awt.TextArea();
        textArea3 = new java.awt.TextArea();
        textArea4 = new java.awt.TextArea();
        textArea5 = new java.awt.TextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        textArea7 = new java.awt.TextArea();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        textArea1 = new java.awt.TextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        textArea6 = new java.awt.TextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea9 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        textArea8 = new java.awt.TextArea();
        normalBtn = new javax.swing.JButton();
        obstacleBtn = new javax.swing.JButton();
        lowBateryBtn = new javax.swing.JButton();
        droneCrashBtn = new javax.swing.JButton();
        weatherConditionsBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        viewPartialBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();

        coordinates.setBounds(bounds());
        coordinates.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        coordinates.getContentPane().add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 60, 30));
        coordinates.getContentPane().add(jSpinner3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 60, 30));
        coordinates.getContentPane().add(jSpinner4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 60, 30));
        coordinates.getContentPane().add(jSpinner5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 60, 30));
        coordinates.getContentPane().add(jSpinner6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 60, 30));
        coordinates.getContentPane().add(jSpinner7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 60, 30));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N", "E", "S", "W" }));
        coordinates.getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 50, 30));

        jTextField5.setText("D");
        coordinates.getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 20, 30));

        jTextField6.setText("S");
        coordinates.getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 20, 30));

        jTextField7.setText("D");
        coordinates.getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 20, 30));

        jTextField8.setText("M");
        coordinates.getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 20, 30));

        jTextField9.setText("M");
        coordinates.getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 20, 30));

        jTextField10.setText("S");
        coordinates.getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 20, 30));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N", "E", "S", "W" }));
        coordinates.getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 50, 30));

        jButton6.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jButton6.setText("Enter");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        coordinates.getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 80, 40));

        jLabel4.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel4.setText("Select the coordinates of the area to map: ");
        coordinates.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 70));

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel5.setText("Longitude:");
        coordinates.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel6.setText("Latitude:");
        coordinates.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        sending.setMessage("Your request is being sent to the manager drone.");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maps/ebeematterhorn-12.jpg"))); // NOI18N

        javax.swing.GroupLayout mapLayout = new javax.swing.GroupLayout(map.getContentPane());
        map.getContentPane().setLayout(mapLayout);
        mapLayout.setHorizontalGroup(
            mapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );
        mapLayout.setVerticalGroup(
            mapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new java.awt.CardLayout());

        jPanel3.setBackground(new java.awt.Color(182, 215, 215));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Manager Drone");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel7.setText("Prioritizing Module");

        jLabel9.setText("Core Work Module");

        jLabel10.setText("Data Assembly Module");

        jLabel11.setText("Drone Planning Module");

        jLabel13.setText("Communication sub-module: Heartbeat");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(108, 108, 108))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(92, 92, 92))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textArea3, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                    .addComponent(textArea5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textArea2, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                    .addComponent(textArea4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(textArea7, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(202, 202, 202))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 161, 161))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textArea3, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(textArea2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textArea4, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textArea5, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textArea7, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(182, 215, 215));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Manager System");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(textArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(textArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(182, 215, 215));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel12.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Worker Drone");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        textArea9.setColumns(20);
        textArea9.setRows(5);
        jScrollPane1.setViewportView(textArea9);

        jLabel1.setText("Heartbeat");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textArea6, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(138, 138, 138))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(textArea6, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jPanel6.setBackground(new java.awt.Color(182, 215, 215));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel14.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Transporter Drone");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textArea8, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textArea8, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        normalBtn.setBackground(new java.awt.Color(0, 153, 153));
        normalBtn.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        normalBtn.setText("Request Mapping (Typical)");
        normalBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153)));
        normalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalBtnActionPerformed(evt);
            }
        });

        obstacleBtn.setBackground(new java.awt.Color(0, 153, 153));
        obstacleBtn.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        obstacleBtn.setText("Request Mapping + Obstacle");
        obstacleBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153)));
        obstacleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obstacleBtnActionPerformed(evt);
            }
        });

        lowBateryBtn.setBackground(new java.awt.Color(0, 153, 153));
        lowBateryBtn.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        lowBateryBtn.setText("Request Mapping + Low Batery");
        lowBateryBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153)));
        lowBateryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowBateryBtnActionPerformed(evt);
            }
        });

        droneCrashBtn.setBackground(new java.awt.Color(0, 153, 153));
        droneCrashBtn.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        droneCrashBtn.setText("Request Mapping + Drone Crash");
        droneCrashBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153)));
        droneCrashBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                droneCrashBtnActionPerformed(evt);
            }
        });

        weatherConditionsBtn.setBackground(new java.awt.Color(0, 153, 153));
        weatherConditionsBtn.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        weatherConditionsBtn.setText("Request Mapping + Weather Conditions");
        weatherConditionsBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153)));
        weatherConditionsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weatherConditionsBtnActionPerformed(evt);
            }
        });

        viewPartialBtn.setBackground(new java.awt.Color(0, 153, 153));
        viewPartialBtn.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        viewPartialBtn.setText("View Partial Result");
        viewPartialBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewPartialBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPartialBtnActionPerformed(evt);
            }
        });

        clearBtn.setBackground(new java.awt.Color(0, 153, 153));
        clearBtn.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.setActionCommand("Clear");
        clearBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dronesPanelLayout = new javax.swing.GroupLayout(dronesPanel);
        dronesPanel.setLayout(dronesPanelLayout);
        dronesPanelLayout.setHorizontalGroup(
            dronesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dronesPanelLayout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addGroup(dronesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(dronesPanelLayout.createSequentialGroup()
                        .addGroup(dronesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dronesPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(dronesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(droneCrashBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(weatherConditionsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(dronesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(dronesPanelLayout.createSequentialGroup()
                                .addComponent(viewPartialBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(135, 135, 135)
                                .addComponent(clearBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(normalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(92, 92, 92)
                        .addGroup(dronesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lowBateryBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(obstacleBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(dronesPanelLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        dronesPanelLayout.setVerticalGroup(
            dronesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dronesPanelLayout.createSequentialGroup()
                .addGroup(dronesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dronesPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(normalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dronesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dronesPanelLayout.createSequentialGroup()
                                .addGap(0, 28, Short.MAX_VALUE)
                                .addComponent(lowBateryBtn)
                                .addGap(31, 31, 31))
                            .addGroup(dronesPanelLayout.createSequentialGroup()
                                .addGroup(dronesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(weatherConditionsBtn)
                                    .addComponent(viewPartialBtn)
                                    .addComponent(clearBtn))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(dronesPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(dronesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(droneCrashBtn)
                            .addComponent(obstacleBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dronesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(dronesPanelLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        mainPanel.add(dronesPanel, "Drone Swarm System");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void droneCrashBtnActionPerformed(java.awt.event.ActionEvent evt) {                                              
       //Checking Available drones
       numberOfSteps = 24;
       startingStep = 9;
       switch(stepN){
           case 0:
                textArea8.append("TD[1]:Charging... (23 minutes to full charge)\nTD[2]:Charging... (24 minutes to full charge)\nTD[3]:Charging... (5 minutes to full charge)\nTD[4]:Charging... (5 minutes to full charge)\n");
                textArea4.append("Charging\n");
                textArea1.append("Checking Available Drones...\n");
                stepN++;
            break;
            case 1:textArea3.append("MD[3]: Sending Acknoledgement to Main....\n");
                stepN++;
            break;
            case 2: textArea3.append("MD[4]: Sending Acknoledgement to Main....\n");
                stepN++;
            break;
            case 3: 
                textArea3.append("MD[2]: Sending Acknoledgement to Main....\n");
                textArea3.append("MD[1]: Sending Acknoledgement to Main....\n");
                stepN++;
            break;
            case 4:textArea1.append("MD[3] Ack received  (5 seconds)\nMD[4] Ack received  (4 seconds)\nMD[2] Ack received  (6 seconds)\nMD[1] Ack received  (4 seconds)\n");
                stepN++;
            break;
            case 5:textArea1.append("MD[3][4][2] were picked. (5 second average to respond)\n");
                textArea1.append("Notifying selected Manager Drones...\n");
                stepN++;
            break;
            case 6:
                textArea3.append("MD[3]: Initializing worker drones (average of 8 seconds needed)\nMD[4]: Initializing worker drones (average of 8 seconds needed)\nMD[2]: Initializing worker drones (average of 7 seconds needed)\n");
                threadHB.start();
                threadHBS.start();
                stepN++;
            break;
            case 7:
                textArea2.append("MD[3]: Generating 20 subtasks (47 minutes needed)\nMD[4]: Generating 18 subtasks (47 minutes needed)\nMD[2]: Generating 20 subtasks (39 minutes needed)\n");
                textArea4.setText(""); textArea4.setText("Executing Mission\nCharging");
                stepN++;
            break;
            case 8:
                textArea2.append("MD[3]:Assigning subtask 1-10 to #323WD/#334WD/#354WD/#322WD/#364WD/#374WD/#347WD/#375WD/#354WD/#312WD\n");
                textArea2.append("MD[4]:Assigning subtask 1-10 to #423WD/#434WD/#454WD/#422WD/#464WD/#474WD/#447WD/#475WD/#454WD/#412WD\n");
                textArea2.append("MD[2]:Assigning subtask 1-10 to #223WD/#234WD/#254WD/#222WD/#264WD/#274WD/#247WD/#275WD/#254WD/#212WD\n");
                textArea3.append("Assigning Tasks to working Drones...\n");
                
                stepN++;
            break;
            case 9: 
                textArea6.append("WD[312->322]:Collecting Data... (4.80GB / 23 minutes needed)\n");
                textArea6.append("WD[412->422]:Collecting Data... (4.23GB / 22 minutes needed)\n");
                textArea6.append("WD[212->222]:Collecting Data... (4.63GB / 23 minutes needed)\n");
                threadDC.start();
                viewPartialBtn.setVisible(true);
                stepN++;
            break;
            case 10: 
                textArea7.append("WD[4]: Drone #465WD is not responding (13 seconds)\n");
                stepN++;
            break;
            case 11: 
                textArea7.append("WD[4]: Drone #465WD is not responding (23 seconds)\n");
                stepN++;
            break;
            case 12: 
                textArea3.append("WD[4]: Drone #465WD Crashed...\n");
                stepN++;
            break;
            case 13:
                textArea4.setText(""); textArea4.setText("Notify Drone Crash\nExecuting Mission\nCharging\n"); 
                textArea1.append("Initiating Drone Retrieval Program (9 minutes needed)\n");
                textArea1.append("Checking Availability of Transporter Drone\n");
                stepN++;
            break;
            case 14:
                 textArea8.append("Sending Acknowledgement...\n");
                stepN++;
            break;
            case 15:
                textArea1.append("TD acknowledgement receieved\n");
                textArea1.append("Deploying Transporter Drones\n");
                stepN++;
            break;
            case 16:
                textArea1.append("Assigning Replacement MD[4] (234 in stock)\n");
                stepN++;
               break;
            case 17:
                textArea3.append("Deploying new Drone\n");
                textArea8.append("Crashed Drone Retrieved Notification\n");
                textArea4.setText(""); textArea4.append("Deploy New Drone\nExecuting Mission\nCharging");
                stepN++;
               break;
            case 18:
                textArea1.append("Crashed Drone Retrieved (11 minutes needed)\n");
                textArea3.append("MD[4]: Assign Task to new #483WD\n");
                textArea4.setText(""); textArea4.append("Executing Mission\nCharging\n");
                stepN++;
               break;
            case 19: 
                textArea6.append("WD[312->322]:Completed \n");
                textArea6.append("WD[412->422]:Completed \n");
                textArea6.append("WD[212->222]:Completed \n");
                threadDC.stop();
                stepN++;
            break;
             case 20:
                textArea2.append("MD[3]:Assigning subtask 11-20 to #323WD/#334WD/#354WD/#322WD/#364WD/#374WD/#347WD/#375WD/#354WD/#312WD\n");
                textArea2.append("MD[4]:Assigning subtask 11-18 to #423WD/#434WD/#454WD/#422WD/#464WD/#474WD/#447WD/#475WD/#454WD/#412WD\n");
                textArea2.append("MD[2]:Assigning subtask 11-20 to #223WD/#234WD/#254WD/#222WD/#264WD/#274WD/#247WD/#275WD/#254WD/#212WD\n");
                
                stepN++;
            break;
            case 21: 
                textArea6.append("WD[312->322]:Collecting Data... (3.80GB / 23 minutes needed)\n");
                textArea6.append("WD[412->422]:Collecting Data... (1.23GB / 16 minutes needed)\n");
                textArea6.append("WD[212->222]:Collecting Data... (4.63GB / 23 minutes needed)\n");
                threadDC.resume();
                stepN++;
            break;
            case 22: 
                textArea6.append("WD[312->322]:Completed \n");
                textArea6.append("WD[412->422]:Completed \n");
                textArea6.append("WD[212->222]:Completed \n");
                threadDC.stop();
                stepN++;
            break;
            case 23:  
                    threadHB.stop();
                    threadHBS.stop();

                    textArea3.append("Task Completed\n");
                    textArea4.setText(""); textArea4.append("Ordering WD to land in base\nCharging\n");
                    textArea3.append("Sending Result to Main\n");
                    textArea6.append("Landing...\n");
                 stepN++;
               break;
            case 24:
                textArea1.append("Assembling Final Result...\n");
                textArea6.append("Landed...\nCharing...\n");
                 try {
                     TimeUnit.SECONDS.sleep(3);
                 } catch (InterruptedException ex) {
                     Logger.getLogger(prototype.class.getName()).log(Level.SEVERE, null, ex);
                 }  
                 jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maps/4.jpg"))); 
                map.setSize(new Dimension(686, 600));
                map.setVisible(true);
                stepN++;
                viewPartialBtn.setVisible(false);
                
               break;
             
            default:
                stepN=0;
            
       }

        
        
    }                                             
     
    private void weatherConditionsBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "Drone Swarm System");
    }                                                    

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        JOptionPane.showMessageDialog(sending, "You request is being sent to the manager drone");
    }                                        

    private void obstacleBtnActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void lowBateryBtnActionPerformed(java.awt.event.ActionEvent evt) {                                             
        switch(stepN){
            case 0:
                textArea1.append("Request Received from Controller Manager System...\n");
                stepN++;
               break;
            case 1:
                textArea1.append("Checking Available Drones...\n");
                textArea3.append("MD[3]: Sending Acknoledgement to Manager System....\n");
                textArea3.append("MD[4]: Sending Acknoledgement to Manager System....\n");
                textArea3.append("MD[2]: Sending Acknoledgement to Manager System....\n");
                textArea3.append("MD[1]: Sending Acknoledgement to Manager System....\n");
                stepN++;
               break;
            case 2:
                //Selecting First Drone
                 textArea1.append("MD[3][4][2] were picked.\n");
                 stepN++;
               break;
            case 3:
                threadHB.start();
                textArea1.append("Sending Acknoledgemnts...\n");
                textArea2.append("Planning mapping task execution...\n");
                stepN++;
               break;
            case 4:
                textArea2.append("MD[2]:Generating Working drone's Tasks\n");
                textArea2.append("MD[4]:Generating Working drone's Tasks\n");
                textArea2.append("MD[3]:Generating Working drone's Tasks\n");
                stepN++;
               break;
            case 5:
                textArea3.append("Assigning Tasks to working Drones...\n");
                stepN++;
               break;
            case 6:
                textArea6.append("Mapping request received from MD\n");
                textArea6.append("Sending request acknowledgement to MD\n");
                stepN++;
               break;
            case 7:
                threadDC.start();
                stepN++;
               break;
            case 8: 
                textArea6.append("Collecting Data...\n");
                stepN++;
               break;
            case 9:                
                textArea6.append("WD: Low Battery \n");     
                textArea6.append("WD: Reporting low battery warning to Manager Drone...\n");
                stepN++;
               break;
            case 10:
                textArea3.append("MD:Low Battery Report received from WD#16\n");
                stepN++;
                break;
            case 11:
                textArea4.append("Detecting higher priority task: Low Battery Warning....\n");
                textArea4.append("Saving current tasks state....\n");
                stepN++;
               break;
            case 12:
               textArea4.append("Preemting current tasks....\n");
               stepN++;
               break;
            case 13:
                textArea3.append("Sending request to WD#14 to join base...\n");
                textArea3.append("Informing manager system: Drone returning to the base...\n");
                stepN++;
               break;
            case 14:                  
                textArea1.append("WD#14 returning to the base to get charged\n");
                stepN++;
               break;
            case 15:
                textArea6.append("Preparing return to base...\n");
                stepN++;
                break;
            case 16:
                textArea6.append("Landing..\n");
                stepN++;
                break;
            case 17: 
                textArea6.setText("");
                textArea2.append("Replanning WD#16 task...\n");
                textArea2.append("Checking for available drones\n");
                stepN++;
                break;
            case 18:
                textArea2.append("Assign task to WD#23\n");
                textArea3.append("Sending re-assigned task to WD#23\n");
                stepN++;
                break;
            case 19:
                textArea6.append("Mapping request received from MD\n");
                textArea6.append("Sending acknowledgement to MD\n");
                textArea6.append("Executing task...\n");
                stepN++;
                break;
            case 20:
                textArea3.append("WD#23 Acknowledgement received...\n");
                stepN++;
               break;
            case 21:  
                threadDC.stop();
                    textArea3.append("Task Completed\n");
                    textArea3.append("Ordering worker drones to land\n...");
                    textArea3.append("Sending Result to Manager System\n");
                    stepN++;
                    break;
            case 22:
                 textArea6.append("Landing...\n");
                 threadHB.stop();
                 stepN++;
               
               break;
            case 23:
                textArea1.append("Assembling Final Result...\n");
                stepN++;
                break;
            case 24:
                textArea1.append("Map Ready...\n");
                map.setSize(new Dimension(1000, 750));
                map.setVisible(true);
                stepN++;
               break;
            case 25:
                stepN++;
               break;
             
            default:
                stepN=0;
      }
    }                                            

    private void normalBtnActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
            numberOfSteps = 12;
            startingStep = 9;
            switch(stepN){
            case 0:
                textArea1.append("Request Received from Controller Manager System...\n");
                textArea1.append("Checking Available Drones...\n");
                stepN++;
               break;
            case 1:
                textArea3.append("MD[3]: Sending Acknoledgement to Manager Main....\n");
                stepN++;
                break;
            case 2: 
                textArea3.append("MD[4]: Sending Acknoledgement to Manager Main....\n");
                textArea3.append("MD[2]: Sending Acknoledgement to Manager Main....\n");
                stepN++;
                break;
            case 3:
                textArea3.append("MD[1]: Sending Acknoledgement to Manager Main....\n");
                stepN++;
               break;
            case 4:
                //Selecting First Drone
                textArea1.append("MD[3] Ack received  (5 seconds)\nMD[4] Ack received "
                        + " (4 seconds)\nMD[2] Ack received  (6 seconds)\nMD[1] Ack received  (4 seconds)\n");
                 stepN++;
               break;
            case 5: 
                textArea1.append("MD[3][4][2] were picked. (5 second average to respond)\n");
                textArea1.append("Notifying selected Manager Drones...\n");
                stepN++;
               break;
            case 6: 
                textArea3.append("MD[3]: Initializing worker drones (average of 8 seconds needed)\nMD[4]: Initializing worker drones (average of 8 seconds needed)\nMD[2]: Initializing worker drones (average of 7 seconds needed)\n");
                threadHB.start();
                threadHBS.start();
                stepN++;
              break;
            case 7:
                textArea2.append("MD[3]: Generating 10 subtasks (20 minutes needed)\nMD[4]: Generating 10 subtasks (20 minutes needed)\nMD[2]: Generating 10 subtasks (20 minutes needed)\n");
                textArea4.setText(""); textArea4.setText("Executing Mission\nCharging");
                stepN++;
              break;
            case 8:
                textArea2.append("MD[3]:Assigning subtask 1-10 to #323WD/#334WD/#354WD/#322WD/#364WD/#374WD/#347WD/#375WD/#354WD/#312WD\n");
                textArea2.append("MD[4]:Assigning subtask 1-10 to #423WD/#434WD/#454WD/#422WD/#464WD/#474WD/#447WD/#475WD/#454WD/#412WD\n");
                textArea2.append("MD[2]:Assigning subtask 1-10 to #223WD/#234WD/#254WD/#222WD/#264WD/#274WD/#247WD/#275WD/#254WD/#212WD\n");
                textArea3.append("Assigning Tasks to working Drones...\n");
                stepN++;
            break;
            case 9: 
                textArea6.append("WD[312->322]:Collecting Data... (4.80GB / 23 minutes needed)\n");
                textArea6.append("WD[412->422]:Collecting Data... (4.23GB / 22 minutes needed)\n");
                textArea6.append("WD[212->222]:Collecting Data... (4.63GB / 23 minutes needed)\n");
                threadDC.start();
                viewPartialBtn.setVisible(true);
                stepN++;
              break;    
            case 10: 
                textArea6.append("WD[312->322]:Completed \n");
                textArea6.append("WD[412->422]:Completed \n");
                textArea6.append("WD[212->222]:Completed \n");
                threadDC.stop();
                stepN++;
              break;
           
            case 11:  
                threadHB.stop();
                threadHBS.stop();
                textArea3.append("Task Completed\n");
                textArea4.setText(""); textArea4.append("Ordering WD to land in base\nCharging\n");
                textArea3.append("Sending Result to Main\n");
                textArea6.append("Landing...\n");
                stepN++;
               break;
            case 12:
                textArea1.append("Assembling Final Result...\n");
                textArea6.append("Landed...\nCharing...\n");
                try {
                     TimeUnit.SECONDS.sleep(3);
                } catch (InterruptedException ex) {
                     Logger.getLogger(prototype.class.getName()).log(Level.SEVERE, null, ex);
                }  
                jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maps/4.jpg"))); 
                map.setSize(new Dimension(686, 600));
                map.setVisible(true);
                stepN++;
                viewPartialBtn.setVisible(false);
               break;           
            default:
                stepN=0;
      } 
    }                                         

    private void viewPartialBtnActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        int w = 0,h = 0;
        
        String picturePath = "";
        int div = numberOfSteps - startingStep; 
        
        int percent = (stepN - startingStep) * 100 / div;
        System.out.println("Percent:" + percent);
        if(percent >= 0 && percent <= 25){
            w = 686;
            h = 600;
            jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maps/1.jpg"))); 
        }
        else if(percent > 25 && percent <= 65){
            w = 686;
            h = 600;
            jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maps/2.jpg"))); 
        }
        else if(percent > 65 && percent <= 90){
            w = 686;
            h = 600;
            jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maps/3.jpg"))); 
        }
        else {
            System.out.println(getClass().getResource("/map/a.jpg"));
            w = 686;
            h = 600;
            jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maps/4.jpg"))); 
        }
      
       
        GroupLayout mapLayout = new javax.swing.GroupLayout(map.getContentPane());
        
        mapLayout.setHorizontalGroup(
            mapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );
        mapLayout.setVerticalGroup(
            mapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        map.setSize(new Dimension(w, h));
        map.setVisible(true);
    }                                              

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {                                         
       textArea1.setText("");
       textArea2.setText("");
       textArea3.setText("");
       textArea4.setText("");
       textArea5.setText("");
       textArea6.setText("");
       textArea7.setText("");
       textArea8.setText("");
       textArea9.setText("");
       stepN=0;
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prototype.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prototype.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prototype.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prototype.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new prototype().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton clearBtn;
    private javax.swing.JDialog coordinates;
    private javax.swing.JButton droneCrashBtn;
    private javax.swing.JPanel dronesPanel;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JSpinner jSpinner6;
    private javax.swing.JSpinner jSpinner7;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton lowBateryBtn;
    private javax.swing.JLayeredPane mainPanel;
    private javax.swing.JDialog map;
    private javax.swing.JButton normalBtn;
    private javax.swing.JButton obstacleBtn;
    private javax.swing.JOptionPane sending;
    public java.awt.TextArea textArea1;
    private java.awt.TextArea textArea2;
    private java.awt.TextArea textArea3;
    private java.awt.TextArea textArea4;
    public static java.awt.TextArea textArea5;
    private java.awt.TextArea textArea6;
    public static java.awt.TextArea textArea7;
    private java.awt.TextArea textArea8;
    public static javax.swing.JTextArea textArea9;
    public static javax.swing.JButton viewPartialBtn;
    private javax.swing.JButton weatherConditionsBtn;
    // End of variables declaration                   
}


